apiVersion: v1
kind: Service
metadata:
  name: hrms-agentic-plugin-service
  labels:
    app.kubernetes.io/name: hrms-agentic-plugin
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: hrms-agentic-plugin
